### ISSUE TITLE
Python implementation / libboost-python-dev version

### ISSUE THREAD

**Issue by kloppjp** [tsenst/RLOFLib#3]
Hey, the python implementation has been compiled against libboost-python-dev version 1.58.0, which is difficult to obtain on the current Ubuntu. As you are not publishing the source code, is there any chance to rebuild it against libboost_python-py27.so instead of libboost_python-py27.so.1.58.0? Thank you!

**Comment by tsenst** [comment]
I will publish the source code next month. Hope that this will solve youre issue.

**Comment by kloppjp** [comment]
@tsenst Thanks a lot, I'm looking forward!
