### ISSUE TITLE
problem about SIMD in calcOpticalFlowSparseRLOF()

### ISSUE THREAD

**Issue by Shane922** [tsenst/RLOFLib#8]
Hi, Im working with sparse optical flow and I found that since opencv4.3.0, SIMD parallelization is available when compiling with SSE4.1. But I don't know how to enable it, could you or anybody show me a simple demo about it? Thanks very much if anybody can help me!

**Comment by 504115681** [comment]
> Hi, Im working with sparse optical flow and I found that since opencv4.3.0, SIMD parallelization is available when compiling with SSE4.1. But I don't know how to enable it, could you or anybody show me a simple demo about it? Thanks very much if anybody can help me!

Hello, have you solved it now, can you give me some help?
